services:
  - type: web
    name: car-management-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.15.0
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    autoDeploy: true